### ISSUE TITLE
If ipmi_port is not provided in the json file, the BareMetalHost is created with :

### ISSUE THREAD

**Issue by e-minguez** [openshift-metalkube/dev-scripts#345]
https://github.com/openshift-metalkube/dev-scripts/blob/8c0e9c645d2c09c8ccccfc9e7a9cee971042d357/11_register_hosts.sh#L17

```
apiVersion: metalkube.org/v1alpha1
kind: BareMetalHost
metadata:
  name: openshift-master-1
spec:
  online: true
  bmc:
    address: ipmi://a.b.c.d:
    credentialsName: openshift-master-1-bmc-secret
  bootMACAddress: 00:11:22:33:44:55

  machineRef:
    name: ostest-master-1
    namespace: openshift-machine-api
```
